name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
template: |
  $CHANGES

  **Full Changelog**: https://github.com/netft/ros-netft/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

categories:
  - title: Added
    labels:
      - enhancement
      - driver
      - ros2-control
  - title: Fixed
    labels:
      - bug
  - title: Documentation
    labels:
      - documentation
  - title: Maintenance
    labels:
      - ci
      - dependencies
      - tests

exclude-labels:
  - skip-changelog

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
      - enhancement
  patch:
    labels:
      - patch
      - bug
      - dependencies
  default: patch
