#include "netft_driver/status.hpp"

#include <cmath>
#include <iomanip>
#include <optional>
#include <sstream>
#include <stdexcept>

namespace netft_driver {
namespace {
constexpr std::uint32_t kRestartLowMax = 0x0000ffffU;
constexpr std::uint32_t kRestartMinBaseline = kRestartLowMax + 1U;
const std::pair<std::uint32_t, const char *> kStatusBits[] = {
  {0x80000000U, "error summary"}, {0x40000000U, "CPU or RAM error"}, {0x20000000U, "digital board error"}, {0x10000000U, "analog board error"}, {0x08000000U, "serial link communication error"}, {0x04000000U, "program memory verification error"}, {0x02000000U, "halted due to configuration errors"}, {0x01000000U, "settings validation error"}, {0x00800000U, "configuration incompatible with calibration"}, {0x00400000U, "network communication failure"}, {0x00200000U, "CAN communication error"}, {0x00100000U, "RDT communication error"}, {0x00080000U, "EtherNet/IP protocol failure"}, {0x00040000U, "DeviceNet protocol failure"}, {0x00020000U, "transducer saturation or A/D error"}, {0x00010000U, "monitor condition latched"}, {0x00004000U, "watchdog timeout error"}, {0x00002000U, "stack check error"}, {0x00001000U, "serial EEPROM I2C failure"}, {0x00000800U, "serial flash SPI failure"}, {0x00000400U, "analog board watchdog timeout"}, {0x00000200U, "excessive strain gage excitation current"}, {0x00000100U, "insufficient strain gage excitation current"}, {0x00000080U, "artificial analog ground out of range"}, {0x00000040U, "analog board power supply too high"}, {0x00000020U, "analog board power supply too low"}, {0x00000010U, "serial link data unavailable"}, {0x00000008U, "reference voltage or power monitoring error"}, {0x00000004U, "internal temperature error"}, {0x00000002U, "HTTP protocol failure"}};
std::string state_name(ClientState state) { switch (state) { case ClientState::Stopped: return "stopped"; case ClientState::Connecting: return "connecting"; case ClientState::Streaming: return "streaming"; case ClientState::Backoff: return "backoff"; case ClientState::Faulted: return "faulted"; } return "unknown"; }
std::string number(double value, int precision) { std::ostringstream out; out << std::fixed << std::setprecision(precision) << value; return out.str(); }
std::string number(std::uint64_t value) { return std::to_string(value); }
std::string sequence(const std::optional<std::uint32_t> & value) { return value ? std::to_string(*value) : "none"; }
std::string fault_name(FaultCode fault) { switch (fault) { case FaultCode::None: return "unknown fault"; case FaultCode::Timeout: return "receive timeout"; case FaultCode::Socket: return "socket failure"; case FaultCode::SeriousStatus: return "serious device status"; case FaultCode::FtStall: return "FT sequence stall"; case FaultCode::FtBackward: return "FT sequence backward"; case FaultCode::MalformedStorm: return "malformed-packet storm"; case FaultCode::Callback: return "sample callback failure"; } return "unknown fault"; }
}

DiagnosticSeverity classify_status(const std::uint32_t status) { return status == 0 ? DiagnosticSeverity::Ok : status == 0x80010000U ? DiagnosticSeverity::Warn : DiagnosticSeverity::Error; }
std::string decode_status(const std::uint32_t status) { if (status == 0) return "healthy"; std::string result; for (const auto & [mask, name] : kStatusBits) if ((status & mask) != 0) { if (!result.empty()) result += ", "; result += name; } return result; }
SequenceObservation RdtSequenceTracker::observe(const std::uint32_t current) { if (!has_last_) { has_last_ = true; previous_ = current; return {SequenceKind::First, 0}; } const std::uint32_t delta = current - previous_; if (delta == 0) return {SequenceKind::Duplicate, 0}; if (delta < 0x80000000U) { previous_ = current; return delta == 1 ? SequenceObservation{SequenceKind::Contiguous, 0} : SequenceObservation{SequenceKind::Gap, delta - 1}; } return {SequenceKind::OutOfOrder, 0}; }
void RdtSequenceTracker::reset() { has_last_ = false; }
void FtSequenceTracker::begin_session() { has_restart_candidate_ = false; }
FtSequenceObservation FtSequenceTracker::observe(const std::uint32_t current) { if (!has_last_) { has_last_ = true; previous_ = current; return {FtSequenceKind::First}; } if (current == previous_) { has_restart_candidate_ = false; return {FtSequenceKind::Stall}; } const std::uint32_t delta = current - previous_; if (delta < 0x80000000U) { previous_ = current; has_restart_candidate_ = false; return {FtSequenceKind::Forward}; } if (previous_ >= kRestartMinBaseline && has_restart_candidate_ && restart_candidate_ <= kRestartLowMax && current <= kRestartLowMax) { const std::uint32_t candidate_delta = current - restart_candidate_; if (candidate_delta > 0 && candidate_delta < 0x80000000U) { previous_ = current; has_restart_candidate_ = false; return {FtSequenceKind::Restart}; } } restart_candidate_ = current; has_restart_candidate_ = true; return {FtSequenceKind::Backward}; }
DiagnosticEvaluator::DiagnosticEvaluator(double expected, double tolerance) : expected_rdt_rate_(expected), rate_tolerance_(tolerance) { if (!std::isfinite(expected) || expected <= 0) throw std::invalid_argument{"expected_rdt_rate must be finite and greater than zero"}; if (!std::isfinite(tolerance) || tolerance < 0 || tolerance > 1) throw std::invalid_argument{"rate_tolerance must be between 0 and 1"}; }
DiagnosticReport DiagnosticEvaluator::evaluate(const HealthSnapshot & s) {
  std::vector<std::pair<std::string, std::string>> values{{"state", state_name(s.state)}, {"sensor", s.sensor_host + ":" + std::to_string(s.sensor_port)}, {"last_rdt_sequence", sequence(s.last_rdt_sequence)}, {"last_ft_sequence", sequence(s.last_ft_sequence)}, {"last_ft_progress", s.last_ft_progress}, {"device_status", "0x" + [&] { std::ostringstream out; out << std::hex << std::nouppercase << std::setw(8) << std::setfill('0') << s.last_status; return out.str(); }()}, {"active_status", decode_status(s.last_status)}, {"receive_rate_hz", number(s.receive_rate, 1)}, {"expected_receive_rate_hz", number(expected_rdt_rate_, 1)}, {"rate_tolerance", number(rate_tolerance_, 3)}, {"publish_rate_hz", number(s.publish_rate, 1)}, {"received_count", number(s.received_count)}, {"published_count", number(s.published_count)}, {"rate_dropped_count", number(s.rate_dropped_count)}, {"device_error_count", number(s.device_error_count)}, {"lost_count", number(s.lost_count)}, {"duplicate_count", number(s.duplicate_count)}, {"out_of_order_count", number(s.out_of_order_count)}, {"ft_stall_count", number(s.ft_stall_count)}, {"ft_backward_count", number(s.ft_backward_count)}, {"ft_restart_count", number(s.ft_restart_count)}, {"malformed_count", number(s.malformed_count)}, {"malformed_storm_threshold", number(kMalformedStormThreshold)}, {"malformed_storm_window", "between_diagnostic_updates"}, {"reconnect_count", number(s.reconnect_count)}, {"timeout_count", number(s.timeout_count)}, {"callback_error_count", number(s.callback_error_count)}, {"last_record_age_s", s.last_record_age ? number(s.last_record_age->count(), 3) : "none"}, {"last_error", s.last_error}};
  const auto report = [&](int level, const std::string & message, const char * key) { return DiagnosticReport{level, message, values, key}; };
  if (s.state == ClientState::Faulted || s.fault_code != FaultCode::None) return report(2, "faulted: " + (s.last_error.empty() ? fault_name(s.fault_code) : s.last_error), "faulted");
  const auto delta = [](std::uint64_t now, std::uint64_t & previous) { const auto value = now >= previous ? now - previous : 0; previous = now; return value; };
  const auto lost = delta(s.lost_count, lost_), device = delta(s.device_error_count, device_error_), timeout = delta(s.timeout_count, timeout_), malformed = delta(s.malformed_count, malformed_), stall = delta(s.ft_stall_count, ft_stall_), backward = delta(s.ft_backward_count, ft_backward_), restart = delta(s.ft_restart_count, ft_restart_);
  if (s.state == ClientState::Backoff) return report(2, "connection lost; reconnecting", "backoff"); if (s.state == ClientState::Stopped) return report(2, "client stopped", "stopped"); const auto severity = classify_status(s.last_status); if (severity == DiagnosticSeverity::Error) return report(2, "device error: " + decode_status(s.last_status), "device_error"); if (device) return report(2, "serious device status observed since last diagnostic", "device_error_event"); if (timeout) return report(2, "receive timeout observed since last diagnostic", "receive_timeout"); if (malformed >= kMalformedStormThreshold) return report(2, "malformed-packet storm: " + std::to_string(malformed) + " packets since last diagnostic", "malformed_storm"); if (stall) return report(2, "FT sequence stalled " + std::to_string(stall) + " times since last diagnostic", "ft_stall"); if (backward) return report(2, "FT sequence moved backward " + std::to_string(backward) + " times since last diagnostic", "ft_backward"); if (s.state == ClientState::Connecting) return report(1, "waiting for first RDT record", "connecting"); if (severity == DiagnosticSeverity::Warn) return report(1, "monitor condition latched", "condition_latch"); if (restart) return report(1, "FT device counter restarted since last diagnostic", "ft_restart"); if (lost) return report(1, std::to_string(lost) + " RDT records lost", "packet_loss"); const double lower = expected_rdt_rate_ * (1 - rate_tolerance_), upper = expected_rdt_rate_ * (1 + rate_tolerance_); if (s.receive_rate < lower || s.receive_rate > upper) return report(1, "receive rate " + number(s.receive_rate, 1) + " Hz outside " + number(lower, 1) + "-" + number(upper, 1) + " Hz", "receive_rate"); if (s.callback_error_count) return report(1, "sample callback has failed", "callback_error"); return report(0, "streaming normally", "healthy");
}
FaultLogThrottle::FaultLogThrottle(double repeat_interval) : repeat_interval_(repeat_interval) { if (!std::isfinite(repeat_interval) || repeat_interval <= 0) throw std::invalid_argument{"repeat_interval must be finite and greater than zero"}; }
bool FaultLogThrottle::should_log(const DiagnosticReport & report, double now) { if (report.level <= 0) { active_ = false; return false; } const std::string key = report.log_key.empty() ? report.message : report.log_key; if (!active_ || report.level != level_ || key != key_ || now - last_log_ >= repeat_interval_) { active_ = true; level_ = report.level; key_ = key; last_log_ = now; return true; } return false; }
}  // namespace netft_driver
